#include "Minecraft/PacketCoder.hpp"
#include "Minecraft/Testing/TestSink.hpp"
#include "Minecraft/Conditional.hpp"
#include "Minecraft/Utils/IO.hpp"

#include <deque>
#include <stdint.h>
#include <iostream>
#include <iomanip>

int main(){
    bool isPresent = true;
    const std::vector<uint8_t> value = {
        0x92, 0x2a, 0x29, 0x5f, 0x14, 0x7a, 0x11, 0x58, 0x64,
        0x5e, 0x20, 0x54, 0x13, 0x70, 0x9c, 0x47, 0x56, 0x76,
    };
    const std::deque<uint8_t> correctResult = {
        0x92, 0x2a, 0x29, 0x5f, 0x14, 0x7a, 0x11, 0x58, 0x64,
        0x5e, 0x20, 0x54, 0x13, 0x70, 0x9c, 0x47, 0x56, 0x76,
    };
    std::deque<uint8_t> result;

    Minecraft::PacketCoder::encode(result, value);

    if (result == correctResult)
        return 0;
    else{
        std::cout << "Tested value: Size: " << value.size() << ", Contents: {" << Minecraft::Utils::formatVectorContents(value) << "}\n";

        std::cout << "Correct bytes:   {" << Minecraft::Utils::formatByteArray(correctResult.begin(), correctResult.end()) << "}\n";
        std::cout << "Generated bytes: {" << Minecraft::Utils::formatByteArray(result.begin(), result.end()) << "}\n";

        return 1;
    }
}